# Generated by Django 4.2.1 on 2023-07-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_menuitem_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ingredients', models.ManyToManyField(to='inventory.ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='RecipeRequirement',
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
        ),
    ]
