# Generated by Django 4.2.1 on 2023-07-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_recipe_remove_menuitem_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
