# Generated by Django 4.2.1 on 2023-07-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_recipe_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(to='inventory.menuitem'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='unit',
            field=models.CharField(default='grams', max_length=10),
        ),
    ]
